### ISSUE TITLE
make gettext 

### ISSUE THREAD

**Issue by meshiguge** [sphinx-doc/sphinx-intl#9] opened 2017-03-04 09:49 UTC
hi, when use  `make gettext `  in my docs, "startswith"  error caused: 

> Exception occurred:
>   File "/Users/xx/anaconda/lib/python2.7/posixpath.py", line 54, in isabs
>     return s.startswith('/')
> AttributeError: StringList instance has no attribute 'startswith'
> The full traceback has been saved in /var/folders/hq/x053v2n52fbbkyd99d_46ywh0000gn/T/sphinx-err-wgSdEl.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
> make: *** [gettext] Error 1

anyone knows how to do ? thanks

**Comment by shimizukawa** [comment] 2017-03-04 15:43
I guess it is caused by `sphinx-build` instead of `sphinx-intl`. So you should file the issue to https://github.com/sphinx-doc/sphinx/issues.

BTW, It seems your sphinx version is not a current maintained version. Please try earlier version of sphinx.
And/or, please let me know a full traceback that is recorded in the saved log file: `/var/folders/hq/x053v2n52fbbkyd99d_46ywh0000gn/T/sphinx-err-wgSdEl.log`

**Comment by meshiguge** [comment] 2017-03-04 22:44
here is the log  : 
===========
packages/sphinx/ext/oldcmarkup.pyc
Traceback (most recent call last):
  File "/Users/xx/anaconda/lib/python2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/Users/xx/anaconda/lib/python2.7/site-packages/sphinx/application.py", line 220, in build
    self.builder.build_update()
  File "/Users/xx/anaconda/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/Users/xx/anaconda/lib/python2.7/site-packages/sphinx/builders/gettext.py", line 177, in build
    I18nBuilder.build(self, docnames, summary, method)
  File "/Users/xx/anaconda/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 279, in build
    self.finish()
  File "/Users/xx/anaconda/lib/python2.7/site-packages/sphinx/builders/gettext.py", line 206, in finish
    for source, line, _ in positions))
  File "/Users/xx/anaconda/lib/python2.7/site-packages/sphinx/builders/gettext.py", line 206, in <genexpr>
    for source, line, _ in positions))
  File "/Users/xx/anaconda/lib/python2.7/site-packages/sphinx/util/osutil.py", line 160, in safe_relpath
    return relpath(path, start)
  File "/Users/xx/anaconda/lib/python2.7/posixpath.py", line 431, in relpath
    path_list = [x for x in abspath(path).split(sep) if x]
  File "/Users/xx/anaconda/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/xx/anaconda/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: StringList instance has no attribute 'startswith'

**Comment by meshiguge** [comment] 2017-03-04 22:46
> I guess it is caused by sphinx-build instead of sphinx-intl
But my `make html` could work well .    It causes error when I use `make gettext` with sphinx-intl

thanks

**Comment by shimizukawa** [comment] 2017-09-12 22:57
It seems that this issue was solved by https://github.com/sphinx-doc/sphinx/issues/3510. So now I close this issue. Thanks.

**Closed** 2017-09-12 22:58 UTC
